{
  "hash": "756c7c035dacf288c204df2bb4c8ffea",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Analysis Walkthrough'\nauthor: 'Mari Roberts'\ndate: '5-13-2025'\nformat:\n  html:\n    css: styles.css\n    embed-resources: true\n    code-fold: true\n    page-layout: full\n    fig_caption: true\n    toc: true\n---\n\n\n\n\n\n## Overview\n\nThis section documents the full analysis process—from data preparation to modeling to interpretation.\n\nFor a summary of insights, visit the [Key Findings](https://calfresh-cfa-exercise.netlify.app/key_findings) page.\\\nFor project context, visit the [About](https://calfresh-cfa-exercise.netlify.app/about) page.\n\n## Application Walkthrough\n\nBefore analyzing the data, I walked through the [GetCalFresh.org](https://www.getcalfresh.org) application process myself. This helped clarify how each field is presented to applicants, which steps are required or optional, and where users might drop-off.\n\n### Key Takeaways\n\n-   **Multilingual support** is available early in the application (English, Spanish, Chinese, Vietnamese), with additional language preferences captured later.\n-   **The application is structured in stages**: household info → income → expenses → contact details → confirmation.\n-   **Applicants get real-time feedback** about possible eligibility or ineligibility.\n-   **Document uploads and interviews aren't required at submission** — they can happen later, which means missing data doesn’t always signal ineligibility.\n-   **Toward the end**, applicants confirm contact information, set preferences (e.g., language, reminders), and indicate interview availability.\n\nThis walkthrough was useful for interpreting behavioral data in context — especially steps that are optional or invisible in the dataset (like phone interviews completed outside the platform).\n\n## About the Data\n\nThis dataset includes 2,046 CalFresh (SNAP) applications submitted through [GetCalFresh.org](GetCalFresh.org) in San Diego County. Each row represents one application and contains:\n\n-   Information reported by the applicant\n-   Activity tracked through the GetCalFresh platform\n-   Final approval outcome provided by the county\n\nThe dataset reflects the user-facing side of the process. It does not capture every factor a county worker might see (e.g., paper documents or offline interviews), but it provides a detailed view of what users did on the site and what happened afterward.\n\n**Key Variables**\n\n| Variable | Description | Notes |\n|-----------------|-----------------------------|--------------------------|\n| `income` | Household income in the last 30 days | Slightly randomized for privacy |\n| `household_size` | Number of people applying | Used to determine income thresholds |\n| `docs_with_app` | Documents uploaded with the application | Optional at time of submission |\n| `docs_after_app` | Documents uploaded after submission | Often submitted after the interview |\n| `had_interview` | Applicant’s self-report of completing the interview | Based on SMS follow-up; may be missing |\n| `completion_time_mins` | Time taken to complete the application | May include pauses or returns |\n| `stable_housing` | Whether applicant rents/owns their sleeping location | Proxy for housing stability |\n| `under18_n`, `over_59_n` | Children or older adults in the household | May influence prioritization or eligibility |\n| `zip` | Applicant ZIP code | May reflect local conditions or access issues |\n| `approved` | Final approval outcome | Provided by the county |\n\n<br>Contextual Notes:\n\n-   **Interview completion** (`had_interview`) comes from an SMS response. Missing values do not confirm whether an interview occurred — only that no reply was recorded.\n-   **Document fields** only include uploads through GetCalFresh. Submissions made by mail, fax, or in person are not tracked here.\n-   **Approval decisions** come from county records and represent real outcomes.\n\nUnderstanding what’s captured — and what’s missing — helped guide how I interpreted variables.\n\n## Exploratory Data Analysis\n\nBefore modeling, I conducted an exploratory analysis to:\n\n-   Understand the distribution and structure of each variable\n-   Identify missingness and data quality issues\n-   Spot early signals related to approval\n-   Prepare features for interpretability and modeling\n\n### Codebook Summary\n\nI created a structured codebook using a function from my own [`databookR`](https://github.com/mr4909/databookR) package. It describes each variable, its type, missingness, and key statistics — and forms the foundation for all further steps.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate codebook\ncodebook <- databookR::databook(exercise_data)\n\n# Style codebook\nfnc_style_reactable_table(\n  data = codebook |> dplyr::select(`Variable Name`, Statistics, dplyr::everything()),\n  columns = list(\n    `Variable Name` = colDef(align = \"left\", width = 200),\n    Statistics = colDef(align = \"left\", html = TRUE, width = 200)\n  )\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"reactable html-widget html-fill-item\" id=\"htmlwidget-f9b27c04307d35830871\" style=\"width:auto;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f9b27c04307d35830871\">{\"x\":{\"tag\":{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"Variable Name\":[\"app_id\",\"completion_time_mins\",\"household_size\",\"income\",\"docs_with_app\",\"docs_after_app\",\"under18_n\",\"over_59_n\",\"stable_housing\",\"had_interview\",\"zip\",\"approved\"],\"Statistics\":[\"Min: 1.0 <br> Avg: 38866.9 <br> Median: 38066.5 <br> Max: 110550.0 <br> SD: 25305.4\",\"Min: 2.3 <br> Avg: 21.4 <br> Median: 10.4 <br> Max: 8551.8 <br> SD: 195.7\",\"Min: 1.0 <br> Avg: 1.8 <br> Median: 1.0 <br> Max: 12.0 <br> SD: 1.3\",\"Min: 0.0 <br> Avg: 936.0 <br> Median: 270.0 <br> Max: 9779.0 <br> SD: 1228.9\",\"Min: 0.0 <br> Avg: 1.3 <br> Median: 0.0 <br> Max: 25.0 <br> SD: 2.2\",\"Min: 0.0 <br> Avg: 0.8 <br> Median: 0.0 <br> Max: 29.0 <br> SD: 2.1\",\"Min: 0.0 <br> Avg: 0.5 <br> Median: 0.0 <br> Max: 6.0 <br> SD: 1.0\",\"Min: 0.0 <br> Avg: 0.1 <br> Median: 0.0 <br> Max: 2.0 <br> SD: 0.3\",\"TRUE: 1186 (58.0%)<br>FALSE: 860 (42.0%)\",\"TRUE: 595 (57.8%)<br>FALSE: 434 (42.2%)\",\"Top 5 Categories:<br>92105 = 162 (7.9%)<br>92114 = 157 (7.7%)<br>92113 = 155 (7.6%)<br>92115 = 133 (6.5%)<br>92154 = 128 (6.3%)\",\"TRUE: 1148 (56.1%)<br>FALSE: 898 (43.9%)\"],\"Variable Type\":[\"numeric\",\"numeric\",\"numeric\",\"numeric\",\"numeric\",\"numeric\",\"numeric\",\"numeric\",\"logical\",\"logical\",\"factor\",\"logical\"],\"Number of Unique Values\":[2046,2046,10,888,19,20,7,3,2,2,28,2],\"Percentage Missing\":[\"0.0%\",\"0.0%\",\"0.2%\",\"0.0%\",\"0.0%\",\"0.0%\",\"0.2%\",\"0.2%\",\"0.0%\",\"49.7%\",\"0.0%\",\"0.0%\"]},\"columns\":[{\"id\":\"Variable Name\",\"name\":\"Variable Name\",\"type\":\"character\",\"minWidth\":70,\"style\":{\"fontFamily\":\"Source Sans 3\"},\"headerStyle\":{\"fontWeight\":\"bold\",\"background\":\"#ece9f9\",\"fontFamily\":\"Source Sans 3\"},\"width\":200,\"align\":\"left\"},{\"id\":\"Statistics\",\"name\":\"Statistics\",\"type\":\"list\",\"minWidth\":70,\"style\":{\"fontFamily\":\"Source Sans 3\"},\"headerStyle\":{\"fontWeight\":\"bold\",\"background\":\"#ece9f9\",\"fontFamily\":\"Source Sans 3\"},\"html\":true,\"width\":200,\"align\":\"left\"},{\"id\":\"Variable Type\",\"name\":\"Variable Type\",\"type\":\"character\",\"minWidth\":70,\"style\":{\"fontFamily\":\"Source Sans 3\"},\"headerStyle\":{\"fontWeight\":\"bold\",\"background\":\"#ece9f9\",\"fontFamily\":\"Source Sans 3\"}},{\"id\":\"Number of Unique Values\",\"name\":\"Number of Unique Values\",\"type\":\"numeric\",\"minWidth\":70,\"style\":{\"fontFamily\":\"Source Sans 3\"},\"headerStyle\":{\"fontWeight\":\"bold\",\"background\":\"#ece9f9\",\"fontFamily\":\"Source Sans 3\"}},{\"id\":\"Percentage Missing\",\"name\":\"Percentage Missing\",\"type\":\"character\",\"minWidth\":70,\"style\":{\"fontFamily\":\"Source Sans 3\"},\"headerStyle\":{\"fontWeight\":\"bold\",\"background\":\"#ece9f9\",\"fontFamily\":\"Source Sans 3\"}}],\"resizable\":true,\"pagination\":false,\"highlight\":true,\"striped\":true,\"compact\":true,\"dataKey\":\"b347ac6bbd8f0c3208321f8afeb08f32\"},\"children\":[]},\"class\":\"reactR_markup\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n<br>I next reviewed distributions of numeric variables to check for skew, outliers, and interpretability issues.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Custom binwidths depending on variable\nbinwidths <- list(\n  income = 250,\n  completion_time_mins = 40,\n  docs_with_app = 1,\n  docs_after_app = 1,\n  household_size = 1,\n  under18_n = 1,\n  over_59_n = 1\n)\n\n# Generate all plots with custom function\nwrap_plots(\n  fnc_plot_var(\"income\", \"Monthly Income\"),\n  fnc_plot_var(\"completion_time_mins\", \"App Completion Time (Minutes)\", max_x = 120),\n  fnc_plot_var(\"docs_with_app\", \"Docs Uploaded With App\"),\n  fnc_plot_var(\"docs_after_app\", \"Docs Uploaded After App\"),\n  fnc_plot_var(\"household_size\", \"Household Size\"),\n  fnc_plot_var(\"under18_n\", \"Children in Household\"),\n  fnc_plot_var(\"over_59_n\", \"Older Adults in Household\"),\n  ncol = 2\n)\n```\n\n::: {.cell-output-display}\n![](analysis_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n<br>Observations:\n\n- **Income is heavily right-skewed;** most applicants report $0 or very low income (median = $270/month).\n- **Application time is short** for most (median = 10 minutes), but some outliers take hours.\n- **Document uploads are rare** — the majority submit no documents online, either before or after applying.\n- **Household composition:** Most applicants apply alone or with one other person. Few list dependents under 18 or over 59.\n- **Stable housing is reported by only 58%** — suggesting nearly half of applicants face housing instability.\n- **Approval rate = 56%**, with enough variation for modeling.\n- **Interview data is missing for ~50% of cases** — expected, since it’s collected via optional follow-up SMS and not all applicants respond.\n- All other variables are fully or nearly complete.\n\nThis overview helped identify missing or unusual values, clarify behavioral patterns, and flag variables likely to influence approval.\n\n### Correlation and Redundancy Check\n\nBefore modeling, I examined relationships among predictors to identify potential multicollinearity or redundancy. This ensures that coefficients remain stable and interpretable.\n\n**Method 1: Correlation Matrix**\n\nI computed pairwise correlations among numeric variables.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Select numeric predictors\nnum_vars <- exercise_data |>\n  select(income, household_size, under18_n, over_59_n, \n         docs_with_app, docs_after_app, completion_time_mins)\n\n# Compute correlations\ncor_matrix <- cor(num_vars, use = \"complete.obs\")\n\n# Visualize\ncorrplot(cor_matrix, method = \"circle\", type = \"upper\", \n         tl.cex = 2, tl.col = \"black\",\n         col = colorRampPalette(c(cfa_colors$red, \"white\", cfa_colors$blue))(200))\n```\n\n::: {.cell-output-display}\n![](analysis_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n<br>Observations:\n\n- `under18_n` and `household_size` are strongly correlated (r = 0.89), which is expected — families with children are generally larger. \n- `income` and `household_size` are moderately correlated but not collinear in a way that impairs model performance.\n\n**Method 2: Variance Inflation Factor (VIF)**\n\nA Variance Inflation Factor (VIF) measures how much a variable’s estimated coefficient is inflated due to correlation with other predictors — higher values suggest multicollinearity.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Quick VIF check with basic logistic model\nvif_model <- glm(\n  approved ~ income + household_size + under18_n + over_59_n +\n    docs_with_app + docs_after_app + completion_time_mins + \n    stable_housing + had_interview,\n  data = exercise_data,\n  family = binomial()\n)\n\ncar::vif(vif_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              income       household_size            under18_n \n            1.570242             4.949500             4.810768 \n           over_59_n        docs_with_app       docs_after_app \n            1.082801             1.071075             1.094315 \ncompletion_time_mins       stable_housing        had_interview \n            1.012481             1.241863             1.105751 \n```\n\n\n:::\n:::\n\n\n<br>Observations:\n\n- `household_size` (4.95) and `under18_n` (4.81) are near the upper limit but acceptable.\n- `income` (1.57) shows no collinearity concern.\n- All other variables have low VIFs (<1.3), indicating no issues.\n- No variables exceed the common threshold of 5 — multicollinearity is not a concern.\n\nBoth variables `household_size` and `under18_n`, will likely be retained. While correlated, they reflect different eligibility factors: household size affects income limits, while the presence of children may affect processing or priority.\n\n## Approval Rates by Key Variables\n\nTo understand where in the process outcomes start to diverge, I looked at approval rates across key variables. This helped identify patterns worth modeling and showed possible intervention points.\n\n### Interview Completion\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfnc_approval_summary(exercise_data, had_interview)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zseqvdirct\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zseqvdirct table {\n  font-family: 'Source Sans 3';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zseqvdirct thead, #zseqvdirct tbody, #zseqvdirct tfoot, #zseqvdirct tr, #zseqvdirct td, #zseqvdirct th {\n  border-style: none;\n}\n\n#zseqvdirct p {\n  margin: 0;\n  padding: 0;\n}\n\n#zseqvdirct .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zseqvdirct .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zseqvdirct .gt_title {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zseqvdirct .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zseqvdirct .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zseqvdirct .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zseqvdirct .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zseqvdirct .gt_col_heading {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zseqvdirct .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zseqvdirct .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zseqvdirct .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zseqvdirct .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zseqvdirct .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zseqvdirct .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zseqvdirct .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zseqvdirct .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zseqvdirct .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zseqvdirct .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zseqvdirct .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zseqvdirct .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zseqvdirct .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zseqvdirct .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zseqvdirct .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zseqvdirct .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zseqvdirct .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zseqvdirct .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zseqvdirct .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zseqvdirct .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zseqvdirct .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zseqvdirct .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zseqvdirct .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zseqvdirct .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zseqvdirct .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zseqvdirct .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zseqvdirct .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zseqvdirct .gt_left {\n  text-align: left;\n}\n\n#zseqvdirct .gt_center {\n  text-align: center;\n}\n\n#zseqvdirct .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zseqvdirct .gt_font_normal {\n  font-weight: normal;\n}\n\n#zseqvdirct .gt_font_bold {\n  font-weight: bold;\n}\n\n#zseqvdirct .gt_font_italic {\n  font-style: italic;\n}\n\n#zseqvdirct .gt_super {\n  font-size: 65%;\n}\n\n#zseqvdirct .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zseqvdirct .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zseqvdirct .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zseqvdirct .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zseqvdirct .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zseqvdirct .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zseqvdirct .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zseqvdirct .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zseqvdirct div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"had_interview\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">N</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"approval_rate\">Approval Rate (%)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"had_interview\" class=\"gt_row gt_center\">FALSE</td>\n<td headers=\"n\" class=\"gt_row gt_right\">434</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">50.0</td></tr>\n    <tr><td headers=\"had_interview\" class=\"gt_row gt_center\">TRUE</td>\n<td headers=\"n\" class=\"gt_row gt_right\">595</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\" style=\"color: #AF121D; font-weight: bold;\">72.1</td></tr>\n    <tr><td headers=\"had_interview\" class=\"gt_row gt_center\">NA</td>\n<td headers=\"n\" class=\"gt_row gt_right\">1,017</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">49.4</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n<br>Observations:\n\n-   Applicants who reported completing the interview had higher approval rates than those who did not or whose response was missing.\n-   This reinforces the interview as a critical point of potential drop-off.\n-   Missing responses likely indicate no follow-up engagement — not necessarily ineligibility.\n\n### Document Submission Group\n\nI grouped applicants by when (or whether) they submitted documents.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add a doc_group variable \nexercise_data <- exercise_data |> \n  mutate(\n    doc_group = case_when(\n        docs_with_app > 0 & docs_after_app == 0 ~ \"With App Only\",\n        docs_with_app == 0 & docs_after_app > 0 ~ \"After App Only\",\n        docs_with_app > 0 & docs_after_app > 0 ~ \"With + After\",\n        docs_with_app == 0 & docs_after_app == 0 ~ \"No Docs\"\n        ) |> \n      factor(levels = c(\"With App Only\", \"After App Only\", \"With + After\", \"No Docs\"))\n      )\nfnc_approval_summary(exercise_data, doc_group)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yqfdblfikw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yqfdblfikw table {\n  font-family: 'Source Sans 3';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yqfdblfikw thead, #yqfdblfikw tbody, #yqfdblfikw tfoot, #yqfdblfikw tr, #yqfdblfikw td, #yqfdblfikw th {\n  border-style: none;\n}\n\n#yqfdblfikw p {\n  margin: 0;\n  padding: 0;\n}\n\n#yqfdblfikw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yqfdblfikw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yqfdblfikw .gt_title {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yqfdblfikw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yqfdblfikw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yqfdblfikw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqfdblfikw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yqfdblfikw .gt_col_heading {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yqfdblfikw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yqfdblfikw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yqfdblfikw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yqfdblfikw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yqfdblfikw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yqfdblfikw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yqfdblfikw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yqfdblfikw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yqfdblfikw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yqfdblfikw .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yqfdblfikw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfdblfikw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yqfdblfikw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yqfdblfikw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yqfdblfikw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfdblfikw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yqfdblfikw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yqfdblfikw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqfdblfikw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfdblfikw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yqfdblfikw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqfdblfikw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yqfdblfikw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqfdblfikw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yqfdblfikw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfdblfikw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yqfdblfikw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfdblfikw .gt_left {\n  text-align: left;\n}\n\n#yqfdblfikw .gt_center {\n  text-align: center;\n}\n\n#yqfdblfikw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yqfdblfikw .gt_font_normal {\n  font-weight: normal;\n}\n\n#yqfdblfikw .gt_font_bold {\n  font-weight: bold;\n}\n\n#yqfdblfikw .gt_font_italic {\n  font-style: italic;\n}\n\n#yqfdblfikw .gt_super {\n  font-size: 65%;\n}\n\n#yqfdblfikw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yqfdblfikw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yqfdblfikw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yqfdblfikw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yqfdblfikw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yqfdblfikw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yqfdblfikw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yqfdblfikw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yqfdblfikw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"doc_group\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">N</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"approval_rate\">Approval Rate (%)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"doc_group\" class=\"gt_row gt_center\">With App Only</td>\n<td headers=\"n\" class=\"gt_row gt_right\">797</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">65.0</td></tr>\n    <tr><td headers=\"doc_group\" class=\"gt_row gt_center\">After App Only</td>\n<td headers=\"n\" class=\"gt_row gt_right\">248</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">57.3</td></tr>\n    <tr><td headers=\"doc_group\" class=\"gt_row gt_center\">With + After</td>\n<td headers=\"n\" class=\"gt_row gt_right\">213</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\" style=\"color: #AF121D; font-weight: bold;\">65.7</td></tr>\n    <tr><td headers=\"doc_group\" class=\"gt_row gt_center\">No Docs</td>\n<td headers=\"n\" class=\"gt_row gt_right\">788</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">44.2</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n<br>Observations:\n\n-   Approval was highest among applicants who submitted documents with their initial application.\n-   Applicants who submitted documents only after applying had moderately lower rates.\n-   The lowest approval rate (\\~44%) was among those who submitted nothing online.\n\nThis suggests that early document submission may signal follow-through — or speed up processing.\n\n### Housing Stability\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfnc_approval_summary(exercise_data, stable_housing)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"kckmemfdso\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kckmemfdso table {\n  font-family: 'Source Sans 3';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kckmemfdso thead, #kckmemfdso tbody, #kckmemfdso tfoot, #kckmemfdso tr, #kckmemfdso td, #kckmemfdso th {\n  border-style: none;\n}\n\n#kckmemfdso p {\n  margin: 0;\n  padding: 0;\n}\n\n#kckmemfdso .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kckmemfdso .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kckmemfdso .gt_title {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kckmemfdso .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kckmemfdso .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kckmemfdso .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kckmemfdso .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kckmemfdso .gt_col_heading {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kckmemfdso .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kckmemfdso .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kckmemfdso .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kckmemfdso .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kckmemfdso .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kckmemfdso .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kckmemfdso .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kckmemfdso .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kckmemfdso .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kckmemfdso .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kckmemfdso .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kckmemfdso .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kckmemfdso .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kckmemfdso .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kckmemfdso .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kckmemfdso .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kckmemfdso .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kckmemfdso .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kckmemfdso .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kckmemfdso .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kckmemfdso .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kckmemfdso .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kckmemfdso .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kckmemfdso .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kckmemfdso .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kckmemfdso .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kckmemfdso .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kckmemfdso .gt_left {\n  text-align: left;\n}\n\n#kckmemfdso .gt_center {\n  text-align: center;\n}\n\n#kckmemfdso .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kckmemfdso .gt_font_normal {\n  font-weight: normal;\n}\n\n#kckmemfdso .gt_font_bold {\n  font-weight: bold;\n}\n\n#kckmemfdso .gt_font_italic {\n  font-style: italic;\n}\n\n#kckmemfdso .gt_super {\n  font-size: 65%;\n}\n\n#kckmemfdso .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kckmemfdso .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kckmemfdso .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kckmemfdso .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kckmemfdso .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kckmemfdso .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kckmemfdso .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#kckmemfdso .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#kckmemfdso div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stable_housing\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">N</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"approval_rate\">Approval Rate (%)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"stable_housing\" class=\"gt_row gt_center\">FALSE</td>\n<td headers=\"n\" class=\"gt_row gt_right\">860</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\" style=\"color: #AF121D; font-weight: bold;\">64.4</td></tr>\n    <tr><td headers=\"stable_housing\" class=\"gt_row gt_center\">TRUE</td>\n<td headers=\"n\" class=\"gt_row gt_right\">1,186</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">50.1</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n<br>Observations:\n\n-   Applicants reporting unstable housing had higher approval rates.\n-   This may reflect prioritized eligibility for those experiencing housing instability.\n-   Housing instability may increase likelihood of approval due to expedited or simplified eligibility pathways.\n\n### Household Size (Binned)\n\nI binned household size for interpretability.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add bins\nexercise_data <- exercise_data |> \n  mutate(household_size_bin = cut(household_size, breaks = c(0,1,2,3,5,10)))\n\nfnc_approval_summary(exercise_data, household_size_bin)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vgczgnyjhn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vgczgnyjhn table {\n  font-family: 'Source Sans 3';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vgczgnyjhn thead, #vgczgnyjhn tbody, #vgczgnyjhn tfoot, #vgczgnyjhn tr, #vgczgnyjhn td, #vgczgnyjhn th {\n  border-style: none;\n}\n\n#vgczgnyjhn p {\n  margin: 0;\n  padding: 0;\n}\n\n#vgczgnyjhn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vgczgnyjhn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vgczgnyjhn .gt_title {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vgczgnyjhn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vgczgnyjhn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vgczgnyjhn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vgczgnyjhn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vgczgnyjhn .gt_col_heading {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vgczgnyjhn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vgczgnyjhn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vgczgnyjhn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vgczgnyjhn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vgczgnyjhn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vgczgnyjhn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vgczgnyjhn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vgczgnyjhn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vgczgnyjhn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vgczgnyjhn .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vgczgnyjhn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vgczgnyjhn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vgczgnyjhn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vgczgnyjhn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vgczgnyjhn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vgczgnyjhn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vgczgnyjhn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vgczgnyjhn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vgczgnyjhn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vgczgnyjhn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vgczgnyjhn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vgczgnyjhn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vgczgnyjhn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vgczgnyjhn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vgczgnyjhn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vgczgnyjhn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vgczgnyjhn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vgczgnyjhn .gt_left {\n  text-align: left;\n}\n\n#vgczgnyjhn .gt_center {\n  text-align: center;\n}\n\n#vgczgnyjhn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vgczgnyjhn .gt_font_normal {\n  font-weight: normal;\n}\n\n#vgczgnyjhn .gt_font_bold {\n  font-weight: bold;\n}\n\n#vgczgnyjhn .gt_font_italic {\n  font-style: italic;\n}\n\n#vgczgnyjhn .gt_super {\n  font-size: 65%;\n}\n\n#vgczgnyjhn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vgczgnyjhn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vgczgnyjhn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vgczgnyjhn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vgczgnyjhn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vgczgnyjhn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vgczgnyjhn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vgczgnyjhn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vgczgnyjhn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"household_size_bin\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">N</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"approval_rate\">Approval Rate (%)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"household_size_bin\" class=\"gt_row gt_center\">(0,1]</td>\n<td headers=\"n\" class=\"gt_row gt_right\">1,223</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\" style=\"color: #AF121D; font-weight: bold;\">61.7</td></tr>\n    <tr><td headers=\"household_size_bin\" class=\"gt_row gt_center\">(1,2]</td>\n<td headers=\"n\" class=\"gt_row gt_right\">334</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">52.1</td></tr>\n    <tr><td headers=\"household_size_bin\" class=\"gt_row gt_center\">(2,3]</td>\n<td headers=\"n\" class=\"gt_row gt_right\">227</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">45.4</td></tr>\n    <tr><td headers=\"household_size_bin\" class=\"gt_row gt_center\">(3,5]</td>\n<td headers=\"n\" class=\"gt_row gt_right\">228</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">46.1</td></tr>\n    <tr><td headers=\"household_size_bin\" class=\"gt_row gt_center\">(5,10]</td>\n<td headers=\"n\" class=\"gt_row gt_right\">29</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">27.6</td></tr>\n    <tr><td headers=\"household_size_bin\" class=\"gt_row gt_center\">NA</td>\n<td headers=\"n\" class=\"gt_row gt_right\">5</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">60.0</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n<br>Observations:\n\n-   1–2 person households had the highest approval rates.\n-   Larger households saw lower approval rates.\n-   This may be due to stricter income thresholds at higher household sizes — or more complexity in verifying eligibility.\n\n### ZIP Code Variation\n\nZIP code can reflect structural factors that influence access: geography, internet connectivity, support, and even worker caseloads. While it’s not causal, it helps show system-level variation.\n\nI assessed variation in approval rates by ZIP code, filtering out ZIPs with fewer than 10 applications.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregate by ZIP (filter out sparse ZIPs)\nzip_summary <- exercise_data |>\n  group_by(zip) |>\n  summarize(\n    n = n(),\n    approval_rate = mean(approved, na.rm = TRUE)\n  ) |>\n  filter(n >= 10)\n\n# Bar chart\nggplot(zip_summary, aes(x = fct_reorder(zip, approval_rate), \n                        y = approval_rate * 100)) +\n  geom_col(fill = cfa_colors$blue) +\n  coord_flip() +\n  labs(\n    title = \"Approval Rate by ZIP Code (≥10 applications)\",\n    x = \"ZIP Code\",\n    y = \"Approval Rate (%)\"\n  ) +\n  fnc_theme_cfa()\n```\n\n::: {.cell-output-display}\n![](analysis_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n<br>Observations:\n\n-   Approval rates vary from ~34% to ~69% across ZIP codes.\n-   This range is large enough to suggest systematic differences, not just noise.\n-   High- and low-performing ZIPs each have reasonable sample sizes, supporting this concern.\n\n### Statistical Test: Is ZIP Predictive of Approval?\n\nTo formally test whether ZIP code is predictive of approval, I ran a chi-squared test.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nzip_test <- exercise_data |>\n  filter(!is.na(approved), !is.na(zip)) |>\n  count(zip, approved) |>\n  pivot_wider(names_from = approved, values_from = n, values_fill = 0) |>\n  column_to_rownames(\"zip\") |>\n  as.matrix() |>\n  chisq.test()\n\nzip_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  as.matrix(column_to_rownames(pivot_wider(count(filter(exercise_data,     !is.na(approved), !is.na(zip)), zip, approved), names_from = approved,     values_from = n, values_fill = 0), \"zip\"))\nX-squared = 43.85, df = 27, p-value = 0.02143\n```\n\n\n:::\n:::\n\n\n<br>Observations:\n\n-   The chi-squared test was **statistically significant** (p \\< 0.05).\n-   This means approval rates vary by ZIP code more than we'd expect by chance.\n\n### Preparation for Modeling\n\nBefore fitting a model, I created new variables and adjusted a few existing ones to improve interpretability. These changes were grounded in earlier exploratory analysis and CalFresh eligibility rules.\n\nThe goal was to make model coefficients easier to interpret and ensure alignment with how eligibility and case processing work in practice.\n\n**Income**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexercise_data <- exercise_data |>\n  mutate(income_500 = income / 500)\n```\n:::\n\n\n\n-   Scaled income in \\$500 units to make coefficients easier to interpret.\n-   A log-odds change now reflects the effect of each additional \\~\\$500 in monthly income, not each dollar.\n\n**Application Completion Time**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexercise_data <- exercise_data |>\n  mutate(\n    completion_time_capped = if_else(completion_time_mins > 180, 180, completion_time_mins),\n    long_app = completion_time_mins > 60\n  )\n```\n:::\n\n\n\n-   Capped extreme values above 180 minutes to reduce the influence outliers.\n-   Flagged apps that took more than one hour (`long_app`) to explore whether interruptions or complexity affect outcomes.\n\n**Interview Completion (Self-Reported)**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexercise_data <- exercise_data |>\n  mutate(interview_completed = case_when(\n    had_interview == TRUE ~ \"Completed\",\n    TRUE ~ \"Not confirmed\"\n  ) |> factor(levels = c(\"Not confirmed\", \"Completed\")))\n```\n:::\n\n\n\n-   Re-coded `had_interview` into a 2-category factor:\n    -   “Completed” = applicant said they had the interview\n    -   “Not confirmed” = didn’t respond or said no\n-   This avoids misinterpreting missing data as a definitive “no”\n\n## Income Eligibility\n\nTo better understand who should be approved under CalFresh rules, I used the official [income eligibility thresholds](https://dpss.lacounty.gov/en/food/calfresh/gross-income.html) based on household size.\n\nThese limits reflect the 200% Federal Poverty Level under California’s Broad-Based Categorical Eligibility (BBCE) policy.\n\nThis allows us to distinguish:\n\n-   Applicants who likely met income-based eligibility\n-   Applicants who may have been denied despite being income-eligible\n-   The extent to which approval decisions align with income thresholds\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create eligibility table based on the table here:\n# https://dpss.lacounty.gov/en/food/calfresh/gross-income.html\neligibility_table <- tibble::tibble(\n  household_size = 1:15,\n  max_gross_income = c(\n    2510, 3408, 4304, 5200, 6098, 6994, 7890, 8788,\n    9686, 10582, 11478, 12374, 13270, 14166, 15062  # estimate using +896 per person\n  )\n)\n\n# Join with application data\nexercise_data <- exercise_data |>\n  left_join(eligibility_table, by = \"household_size\") |>\n  mutate(\n    income_eligible = income <= max_gross_income\n  )\n\n# Approval summary by income eligibility\napproval_summary <- exercise_data |>\n  group_by(income_eligible) |>\n  summarize(\n    n = n(),\n    approval_rate = mean(approved, na.rm = TRUE),\n    approved_over_income = sum(approved & !income_eligible, na.rm = TRUE),\n    .groups = \"drop\"\n  ) |>\n  mutate(\n    approval_rate = round(approval_rate * 100, 1)\n  )\n\n# Highlight minimum approval rate\nmin_rate <- min(approval_summary$approval_rate, na.rm = TRUE)\n\napproval_summary |>\n  gt::gt() |>\n  gt::cols_label(\n    income_eligible = \"Income-Eligible\",\n    n = \"N\",\n    approval_rate = \"Approval Rate (%)\",\n    approved_over_income = \"Approved Despite High Income\"\n  ) |>\n  gt::fmt_number(columns = c(n, approved_over_income), decimals = 0) |>\n  fnc_style_gt_table()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"sjxgtivlmq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#sjxgtivlmq table {\n  font-family: 'Source Sans 3';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#sjxgtivlmq thead, #sjxgtivlmq tbody, #sjxgtivlmq tfoot, #sjxgtivlmq tr, #sjxgtivlmq td, #sjxgtivlmq th {\n  border-style: none;\n}\n\n#sjxgtivlmq p {\n  margin: 0;\n  padding: 0;\n}\n\n#sjxgtivlmq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#sjxgtivlmq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#sjxgtivlmq .gt_title {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#sjxgtivlmq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#sjxgtivlmq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sjxgtivlmq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sjxgtivlmq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sjxgtivlmq .gt_col_heading {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#sjxgtivlmq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#sjxgtivlmq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#sjxgtivlmq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#sjxgtivlmq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#sjxgtivlmq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#sjxgtivlmq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#sjxgtivlmq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#sjxgtivlmq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#sjxgtivlmq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#sjxgtivlmq .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#sjxgtivlmq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sjxgtivlmq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#sjxgtivlmq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#sjxgtivlmq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#sjxgtivlmq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sjxgtivlmq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#sjxgtivlmq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#sjxgtivlmq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sjxgtivlmq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sjxgtivlmq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#sjxgtivlmq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sjxgtivlmq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#sjxgtivlmq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sjxgtivlmq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sjxgtivlmq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sjxgtivlmq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sjxgtivlmq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sjxgtivlmq .gt_left {\n  text-align: left;\n}\n\n#sjxgtivlmq .gt_center {\n  text-align: center;\n}\n\n#sjxgtivlmq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#sjxgtivlmq .gt_font_normal {\n  font-weight: normal;\n}\n\n#sjxgtivlmq .gt_font_bold {\n  font-weight: bold;\n}\n\n#sjxgtivlmq .gt_font_italic {\n  font-style: italic;\n}\n\n#sjxgtivlmq .gt_super {\n  font-size: 65%;\n}\n\n#sjxgtivlmq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#sjxgtivlmq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#sjxgtivlmq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#sjxgtivlmq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#sjxgtivlmq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#sjxgtivlmq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#sjxgtivlmq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#sjxgtivlmq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#sjxgtivlmq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"income_eligible\">Income-Eligible</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">N</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"approval_rate\">Approval Rate (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"approved_over_income\">Approved Despite High Income</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"income_eligible\" class=\"gt_row gt_center\">FALSE</td>\n<td headers=\"n\" class=\"gt_row gt_right\">43</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">9.3</td>\n<td headers=\"approved_over_income\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"income_eligible\" class=\"gt_row gt_center\">TRUE</td>\n<td headers=\"n\" class=\"gt_row gt_right\">1,999</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">57.1</td>\n<td headers=\"approved_over_income\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"income_eligible\" class=\"gt_row gt_center\">NA</td>\n<td headers=\"n\" class=\"gt_row gt_right\">4</td>\n<td headers=\"approval_rate\" class=\"gt_row gt_right\">50.0</td>\n<td headers=\"approved_over_income\" class=\"gt_row gt_right\">0</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n<br>Observations:\n\n-   Most applicants appear income-eligible.\n-   A small number were approved despite exceeding income thresholds — potentially due to exceptions, data entry errors, or income verification.\n-   Nearly half of income-eligible applicants were not approved, pointing to process barriers like missed interviews or incomplete documentation.\n\nThis flag helps contextualize approval decisions in the model, especially when eligible applicants are denied.\n\n## Logistic Regression\n\nTo identify factors most strongly associated with CalFresh approval, I fit a logistic regression model. This model estimates the likelihood of approval based on eligibility-related variables and applicant actions observed through the application process.\n\n### Variable Selection Rationale\n\nI included variables based on:\n\n-   Program relevance (e.g., income, household size)\n-   User experience (e.g., document upload, interview)\n-   Results from earlier exploratory analysis\n\nThe final model uses:\n\n-   Scaled income: `income_500`\n-   Household composition: `household_size`, `under18_n`, `over_59_n`\n-   Document submission: `docs_with_app`, `docs_after_app`\n-   Time spent applying: `completion_time_capped`\n-   Housing stability: `stable_housing`\n-   Interview completion: `interview_completed` (re-coded)\n\n### Model Specification\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\napproval_model <- glm(\n  approved ~ income_500 + household_size + under18_n + over_59_n +\n    docs_with_app + docs_after_app + completion_time_capped +\n    stable_housing + interview_completed,\n  data = exercise_data,\n  family = binomial()\n)\n\nsummary(approval_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = approved ~ income_500 + household_size + under18_n + \n    over_59_n + docs_with_app + docs_after_app + completion_time_capped + \n    stable_housing + interview_completed, family = binomial(), \n    data = exercise_data)\n\nCoefficients:\n                              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)                   0.628432   0.131272   4.787 1.69e-06 ***\nincome_500                   -0.412618   0.029816 -13.839  < 2e-16 ***\nhousehold_size               -0.125768   0.088893  -1.415  0.15712    \nunder18_n                     0.300545   0.117048   2.568  0.01024 *  \nover_59_n                     0.121020   0.155961   0.776  0.43777    \ndocs_with_app                 0.116576   0.025326   4.603 4.16e-06 ***\ndocs_after_app                0.075872   0.027076   2.802  0.00507 ** \ncompletion_time_capped       -0.001958   0.002632  -0.744  0.45674    \nstable_housingTRUE           -0.086942   0.112313  -0.774  0.43887    \ninterview_completedCompleted  1.098309   0.118276   9.286  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 2800.1  on 2041  degrees of freedom\nResidual deviance: 2373.5  on 2032  degrees of freedom\n  (4 observations deleted due to missingness)\nAIC: 2393.5\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n<br>Observations:\n\n-   **Interview completed** had the strongest association with approval.\n-   **Higher income** reduced the odds of approval, as expected.\n-   **Document uploads** (both with and after application) were positively associated with approval.\n-   **Each additional child** was associated with higher approval odds.\n-   **Other variables** (e.g., housing stability, household size, older adults, app time) were not significant once the above were accounted for.\n\n### Odds Ratios and Confidence Intervals\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_results <- broom::tidy(approval_model, exponentiate = TRUE, conf.int = TRUE)\n\nmodel_results |>\n  select(term, estimate, conf.low, conf.high, p.value) |>\n  mutate(across(where(is.numeric), round, 2)) |>\n  gt::gt() |>\n  gt::cols_label(\n    term = \"Variable\",\n    estimate = \"Odds Ratio\",\n    conf.low = \"95% CI (Low)\",\n    conf.high = \"95% CI (High)\",\n    p.value = \"P-Value\"\n  ) |>\n  fnc_style_gt_table()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"dxximtvsvq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dxximtvsvq table {\n  font-family: 'Source Sans 3';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dxximtvsvq thead, #dxximtvsvq tbody, #dxximtvsvq tfoot, #dxximtvsvq tr, #dxximtvsvq td, #dxximtvsvq th {\n  border-style: none;\n}\n\n#dxximtvsvq p {\n  margin: 0;\n  padding: 0;\n}\n\n#dxximtvsvq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dxximtvsvq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dxximtvsvq .gt_title {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dxximtvsvq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dxximtvsvq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dxximtvsvq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dxximtvsvq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dxximtvsvq .gt_col_heading {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dxximtvsvq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dxximtvsvq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dxximtvsvq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dxximtvsvq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dxximtvsvq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dxximtvsvq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dxximtvsvq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dxximtvsvq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dxximtvsvq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dxximtvsvq .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dxximtvsvq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxximtvsvq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dxximtvsvq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dxximtvsvq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dxximtvsvq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxximtvsvq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dxximtvsvq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dxximtvsvq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dxximtvsvq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxximtvsvq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dxximtvsvq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dxximtvsvq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dxximtvsvq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dxximtvsvq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dxximtvsvq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxximtvsvq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dxximtvsvq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxximtvsvq .gt_left {\n  text-align: left;\n}\n\n#dxximtvsvq .gt_center {\n  text-align: center;\n}\n\n#dxximtvsvq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dxximtvsvq .gt_font_normal {\n  font-weight: normal;\n}\n\n#dxximtvsvq .gt_font_bold {\n  font-weight: bold;\n}\n\n#dxximtvsvq .gt_font_italic {\n  font-style: italic;\n}\n\n#dxximtvsvq .gt_super {\n  font-size: 65%;\n}\n\n#dxximtvsvq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dxximtvsvq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dxximtvsvq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dxximtvsvq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dxximtvsvq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dxximtvsvq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dxximtvsvq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dxximtvsvq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#dxximtvsvq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">Variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">Odds Ratio</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">95% CI (Low)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">95% CI (High)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">P-Value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.87</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">1.45</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">2.43</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">income_500</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.66</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.62</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.70</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">household_size</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.88</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.74</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.05</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.16</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">under18_n</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.35</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">1.07</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.70</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.01</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">over_59_n</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.13</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.83</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.53</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.44</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">docs_with_app</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.12</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">1.07</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.18</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">docs_after_app</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.08</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">1.02</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.14</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.01</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">completion_time_capped</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.99</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.46</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">stable_housingTRUE</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.92</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.74</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">1.14</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.44</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">interview_completedCompleted</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">3.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">2.38</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">3.79</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n<br>Observations: \n\n-   An odds ratio \\> 1 means the variable is associated with a higher chance of approval\n-   An odds ratio \\< 1 means a lower chance\n-   Interview completed: \\~3x higher odds of approval\n-   Each \\$500 in income: \\~34% lower odds\n-   Each document uploaded with the application: \\~12% higher odds\n-   Each child (under 18): \\~35% higher odds\n\nThese results reinforce earlier descriptive findings — but also show that certain variables (like app duration or housing status) have little added explanatory value once core factors are controlled for.\n\n## Diagnostics\n\nAfter fitting the logistic regression, I ran several checks to evaluate how well the model fits the data and whether the results are trustworthy. These diagnostics focus on:\n\n-   How much variation the model explains\n-   Whether predicted probabilities align with actual outcomes\n-   How well the model distinguishes approved vs. denied applications\n\n**1. McFadden's Psuedo R²**\n\nDefinition: A measure of how much better the model fits the data compared to a model with no predictors (just an intercept).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pseudo R-squared\npscl::pR2(approval_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfitting null model for pseudo-r2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          llh       llhNull            G2      McFadden          r2ML \n-1186.7634616 -1400.0644571   426.6019909     0.1523508     0.1885348 \n         r2CU \n    0.2526548 \n```\n\n\n:::\n:::\n\n\n\nThe **pseudo R² was around 0.15**, which indicates a moderate effect size. That’s typical in behavioral data, where many influencing factors aren’t captured in the dataset.\n\n**2. Hosmer–Lemeshow Goodness-of-Fit Test**\n\nThis test checks whether the model’s predicted probabilities align with the actual outcomes. It groups observations into deciles by predicted probability, then compares predicted vs. actual approval rates in each group.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhoslem.test(approval_model$y, fitted(approval_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tHosmer and Lemeshow goodness of fit (GOF) test\n\ndata:  approval_model$y, fitted(approval_model)\nX-squared = 9.0452, df = 8, p-value = 0.3385\n```\n\n\n:::\n:::\n\n\n\nOur p-value is 0.34, which is **not staistically significant**. That’s good — it means there’s no evidence of poor fit. The model’s predictions are consistent with observed data.\n\n**3. ROC Curve and AUC (Area Under the Curve)**\n\nAUC summarizes how well the model distinguishes between approved and denied applicants.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_data <- model.frame(approval_model)\nactual <- model_data$approved\npredicted <- fitted(approval_model)\n\nroc_obj <- roc(actual, predicted)\nplot(roc_obj, col = cfa_colors$blue, lwd = 2)\n```\n\n::: {.cell-output-display}\n![](analysis_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n\n```{.r .cell-code}\npROC::auc(roc_obj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArea under the curve: 0.7563\n```\n\n\n:::\n:::\n\n\n\n<br>Observations:\n\n-   AUC = 0.76 means the model assigns a higher predicted probability to an approved case than a denied one 76% of the time.\n-   That’s considered good performance for a logistic model using only observable application behaviors.\n\nTogether, these diagnostics show that the model is well-calibrated, explains meaningful variation, and performs reliably — even with known limitations in the dataset.\n\n**4. Train/Test Split**\n\nTo evaluate how well the model generalizes, I randomly split the data into:\n\n-   80% training set (used to fit the model)\n-   20% test set (used to evaluate performance on unseen data)\n\nThe model was re-fit on the training set, and predicted approval probabilities were generated for the test set. AUC was then calculated on these out-of-sample predictions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Split the data\ntrain_idx <- sample(seq_len(nrow(exercise_data)), size = 0.8 * nrow(exercise_data))\ntrain_data <- exercise_data[train_idx, ]\ntest_data  <- exercise_data[-train_idx, ]\n\n# Refit model on training set\napproval_model <- glm(\n  approved ~ income_500 + household_size + under18_n + over_59_n +\n    docs_with_app + docs_after_app + completion_time_capped +\n    stable_housing + interview_completed,\n  data = train_data,\n  family = binomial()\n)\n\n# Predict on test set\ntest_data <- test_data |>\n  mutate(predicted_prob = predict(approval_model, newdata = test_data, type = \"response\"))\n\n# AUC on test data\nroc_test <- roc(test_data$approved, test_data$predicted_prob)\nauc(roc_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArea under the curve: 0.7465\n```\n\n\n:::\n:::\n\n\n\n<br>Observations:\n\n-   AUC on the test set = **0.76**, nearly identical to the in-sample AUC.\n-   The model performs consistently on new data.\n-   There is no sign of overfitting, and the results generalize well to similar applicants.\n\n## Predicted Probabilities\n\nThe logistic regression model produces a predicted probability of approval for each application. These values reflect how likely someone was to be approved, based on their reported information and process steps.\n\nLooking at predicted probabilities helps identify:\n\n-   Who was almost certain to be approved or denied\n-   Who was in a gray zone, where approval was uncertain\n-   Where small changes — like completing an interview — might make a difference\n\n### Distribution of Predicted Probabilities\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_data <- model.frame(approval_model) |>\n  mutate(predicted_prob = predict(approval_model, type = \"response\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(model_data, aes(x = predicted_prob)) +\n  geom_histogram(fill = cfa_colors$blue, color = \"white\", bins = 30) +\n  labs(\n    title = \"Predicted Probability of CalFresh Approval\",\n    x = \"Predicted Probability\",\n    y = \"Number of Applicants\"\n  ) +\n  fnc_theme_cfa()\n```\n\n::: {.cell-output-display}\n![](analysis_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n<br>Observations:\n\n-   Most applicants had predicted probabilities between 0.3 and 0.8, with two peaks:\n    -   A major peak centered around 0.65\n    -   A secondary peak around 0.8\n-   There are fewer applicants with very low (near 0) or very high (near 1) probabilities, which makes sense — no single factor fully determines approval.\n\nThe distribution suggests real variability in approval likelihood — and that many applicants fall into a moderate range of uncertainty, not extremes.\n\n### Example: Interview Completion\n\nTo show how much one variable matters, I compared average predicted probabilities by interview status:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_data |>\n  group_by(interview_completed) |>\n  summarize(\n    mean_pred_prob = round(mean(predicted_prob), 2),\n    n = n()\n  ) |>\n  gt::gt() |>\n  gt::cols_label(\n    interview_completed = \"Interview Completed\",\n    mean_pred_prob = \"Avg. Predicted Probability\",\n    n = \"N\"\n  ) |>\n  gt::fmt_number(columns = n, decimals = 0) |>\n  fnc_style_gt_table()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"foagmeqqsf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#foagmeqqsf table {\n  font-family: 'Source Sans 3';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#foagmeqqsf thead, #foagmeqqsf tbody, #foagmeqqsf tfoot, #foagmeqqsf tr, #foagmeqqsf td, #foagmeqqsf th {\n  border-style: none;\n}\n\n#foagmeqqsf p {\n  margin: 0;\n  padding: 0;\n}\n\n#foagmeqqsf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#foagmeqqsf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#foagmeqqsf .gt_title {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#foagmeqqsf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#foagmeqqsf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#foagmeqqsf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#foagmeqqsf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#foagmeqqsf .gt_col_heading {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#foagmeqqsf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#foagmeqqsf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#foagmeqqsf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#foagmeqqsf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#foagmeqqsf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#foagmeqqsf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#foagmeqqsf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#foagmeqqsf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#foagmeqqsf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#foagmeqqsf .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#foagmeqqsf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#foagmeqqsf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#foagmeqqsf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#foagmeqqsf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#foagmeqqsf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#foagmeqqsf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#foagmeqqsf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#foagmeqqsf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#foagmeqqsf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#foagmeqqsf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#foagmeqqsf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#foagmeqqsf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#foagmeqqsf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#foagmeqqsf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#foagmeqqsf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#foagmeqqsf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#foagmeqqsf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#foagmeqqsf .gt_left {\n  text-align: left;\n}\n\n#foagmeqqsf .gt_center {\n  text-align: center;\n}\n\n#foagmeqqsf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#foagmeqqsf .gt_font_normal {\n  font-weight: normal;\n}\n\n#foagmeqqsf .gt_font_bold {\n  font-weight: bold;\n}\n\n#foagmeqqsf .gt_font_italic {\n  font-style: italic;\n}\n\n#foagmeqqsf .gt_super {\n  font-size: 65%;\n}\n\n#foagmeqqsf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#foagmeqqsf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#foagmeqqsf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#foagmeqqsf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#foagmeqqsf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#foagmeqqsf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#foagmeqqsf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#foagmeqqsf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#foagmeqqsf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"interview_completed\">Interview Completed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean_pred_prob\">Avg. Predicted Probability</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">N</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"interview_completed\" class=\"gt_row gt_center\">Not confirmed</td>\n<td headers=\"mean_pred_prob\" class=\"gt_row gt_right\">0.49</td>\n<td headers=\"n\" class=\"gt_row gt_right\">1,161</td></tr>\n    <tr><td headers=\"interview_completed\" class=\"gt_row gt_center\">Completed</td>\n<td headers=\"mean_pred_prob\" class=\"gt_row gt_right\">0.72</td>\n<td headers=\"n\" class=\"gt_row gt_right\">472</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n<br>Observations:\n\n-   Applicants who completed the interview had a **72%** average predicted chance of approval\n-   Those who did not (or did not confirm) had just a **50%** chance\n\nThis 22-point gap is one of the clearest signals in the model — and points to a place where better support could help.\n\n### Segmenting Applicants\n\nTo better understand who might benefit from support, I grouped applicants by predicted approval probability. This helps identify:\n\n-   Who is most likely to be approved or denied\n-   Who falls into a gray area, where outcomes are harder to predict\n\nDefine confidence bands:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_data <- model_data |>\n  mutate(prob_band = case_when(\n    predicted_prob < 0.4 ~ \"Low (<40%)\",\n    predicted_prob >= 0.4 & predicted_prob < 0.6 ~ \"Moderate (40–59%)\",\n    predicted_prob >= 0.6 & predicted_prob < 0.8 ~ \"High (60–79%)\",\n    predicted_prob >= 0.8 ~ \"Very High (80%+)\"\n  ) |> factor(levels = c(\"Low (<40%)\", \"Moderate (40–59%)\", \"High (60–79%)\", \"Very High (80%+)\")))\n```\n:::\n\n\n\nSummary by band:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_data |>\n  group_by(prob_band) |>\n  summarize(\n    n = n(),\n    actual_approval_rate = round(mean(approved, na.rm = TRUE) * 100, 1)\n  ) |>\n  gt::gt() |>\n  gt::cols_label(\n    prob_band = \"Predicted Probability Band\",\n    n = \"N\",\n    actual_approval_rate = \"Observed Approval Rate (%)\"\n  ) |>\n  fnc_style_gt_table()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fsyjozqlbv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fsyjozqlbv table {\n  font-family: 'Source Sans 3';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fsyjozqlbv thead, #fsyjozqlbv tbody, #fsyjozqlbv tfoot, #fsyjozqlbv tr, #fsyjozqlbv td, #fsyjozqlbv th {\n  border-style: none;\n}\n\n#fsyjozqlbv p {\n  margin: 0;\n  padding: 0;\n}\n\n#fsyjozqlbv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fsyjozqlbv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fsyjozqlbv .gt_title {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fsyjozqlbv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fsyjozqlbv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fsyjozqlbv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsyjozqlbv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fsyjozqlbv .gt_col_heading {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fsyjozqlbv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fsyjozqlbv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fsyjozqlbv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fsyjozqlbv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fsyjozqlbv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fsyjozqlbv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fsyjozqlbv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fsyjozqlbv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fsyjozqlbv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fsyjozqlbv .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fsyjozqlbv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsyjozqlbv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fsyjozqlbv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fsyjozqlbv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fsyjozqlbv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsyjozqlbv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fsyjozqlbv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fsyjozqlbv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsyjozqlbv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsyjozqlbv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fsyjozqlbv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsyjozqlbv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fsyjozqlbv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsyjozqlbv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fsyjozqlbv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsyjozqlbv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fsyjozqlbv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsyjozqlbv .gt_left {\n  text-align: left;\n}\n\n#fsyjozqlbv .gt_center {\n  text-align: center;\n}\n\n#fsyjozqlbv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fsyjozqlbv .gt_font_normal {\n  font-weight: normal;\n}\n\n#fsyjozqlbv .gt_font_bold {\n  font-weight: bold;\n}\n\n#fsyjozqlbv .gt_font_italic {\n  font-style: italic;\n}\n\n#fsyjozqlbv .gt_super {\n  font-size: 65%;\n}\n\n#fsyjozqlbv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fsyjozqlbv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fsyjozqlbv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fsyjozqlbv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fsyjozqlbv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fsyjozqlbv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fsyjozqlbv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fsyjozqlbv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fsyjozqlbv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"prob_band\">Predicted Probability Band</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">N</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"actual_approval_rate\">Observed Approval Rate (%)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"prob_band\" class=\"gt_row gt_center\">Low (&lt;40%)</td>\n<td headers=\"n\" class=\"gt_row gt_right\">408</td>\n<td headers=\"actual_approval_rate\" class=\"gt_row gt_right\">23.0</td></tr>\n    <tr><td headers=\"prob_band\" class=\"gt_row gt_center\">Moderate (40–59%)</td>\n<td headers=\"n\" class=\"gt_row gt_right\">316</td>\n<td headers=\"actual_approval_rate\" class=\"gt_row gt_right\">48.4</td></tr>\n    <tr><td headers=\"prob_band\" class=\"gt_row gt_center\">High (60–79%)</td>\n<td headers=\"n\" class=\"gt_row gt_right\">654</td>\n<td headers=\"actual_approval_rate\" class=\"gt_row gt_right\">67.9</td></tr>\n    <tr><td headers=\"prob_band\" class=\"gt_row gt_center\">Very High (80%+)</td>\n<td headers=\"n\" class=\"gt_row gt_right\">255</td>\n<td headers=\"actual_approval_rate\" class=\"gt_row gt_right\">85.9</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n<br>Observations:\n\n-   **Very High (80%+):** Most of these applicants were approved — minimal intervention needed.\n-   **High (60–79%):** Still strong performance, but some denials suggest small process gaps (e.g., missing docs).\n-   **Moderate (40–59%):** This is the gray zone — almost half are denied. This group could benefit most from added support.\n-   **Low (\\<40%):** Most were denied, but if any were income-eligible, this may indicate missed opportunities.\n\n### Gray Zone\n\nTo learn more about applicants in the 40–59% predicted range, I created a summary of their characteristics.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get only the rows used in the model\nused_rows <- as.numeric(rownames(model.frame(approval_model)))\n\n# Add predicted probabilities + other variables used in analysis\nmodel_data <- exercise_data[used_rows, ] |>\n  mutate(\n    predicted_prob = predict(approval_model, type = \"response\")\n  )\n\ngray_zone <- model_data |> \n  filter(predicted_prob >= 0.4, predicted_prob < 0.6)\n\ngray_zone_summary <- gray_zone |> \n  summarize(\n    `Number of People` = n(),\n    `Approval Rate` = round(mean(approved, na.rm = TRUE) * 100, 1),\n    `Pct. Income Eligible` = round(mean(income_eligible, na.rm = TRUE) * 100, 1),\n    `Pct. Docs With App` = round(mean(docs_with_app > 0) * 100, 1),\n    `Pct. Docs Acfter App` = round(mean(docs_after_app > 0) * 100, 1),\n    `Pct. Completed Interview` = round(mean(interview_completed == \"Completed\") * 100, 1)\n  )\n\ngray_zone_summary |>\n  pivot_longer(everything()) |>\n  gt::gt() |>\n  gt::cols_label(\n    name = \"Metric\",\n    value = \"%\"\n  ) |>\n  gt::fmt_number(columns = value, decimals = 1) |>\n  fnc_style_gt_table()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"bbdhzepsbe\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#bbdhzepsbe table {\n  font-family: 'Source Sans 3';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#bbdhzepsbe thead, #bbdhzepsbe tbody, #bbdhzepsbe tfoot, #bbdhzepsbe tr, #bbdhzepsbe td, #bbdhzepsbe th {\n  border-style: none;\n}\n\n#bbdhzepsbe p {\n  margin: 0;\n  padding: 0;\n}\n\n#bbdhzepsbe .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#bbdhzepsbe .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#bbdhzepsbe .gt_title {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#bbdhzepsbe .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#bbdhzepsbe .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bbdhzepsbe .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bbdhzepsbe .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bbdhzepsbe .gt_col_heading {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#bbdhzepsbe .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #ECE9F9;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#bbdhzepsbe .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#bbdhzepsbe .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#bbdhzepsbe .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#bbdhzepsbe .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#bbdhzepsbe .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#bbdhzepsbe .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#bbdhzepsbe .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#bbdhzepsbe .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#bbdhzepsbe .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#bbdhzepsbe .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bbdhzepsbe .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#bbdhzepsbe .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#bbdhzepsbe .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#bbdhzepsbe .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bbdhzepsbe .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#bbdhzepsbe .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#bbdhzepsbe .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bbdhzepsbe .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bbdhzepsbe .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#bbdhzepsbe .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bbdhzepsbe .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#bbdhzepsbe .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bbdhzepsbe .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bbdhzepsbe .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bbdhzepsbe .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bbdhzepsbe .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bbdhzepsbe .gt_left {\n  text-align: left;\n}\n\n#bbdhzepsbe .gt_center {\n  text-align: center;\n}\n\n#bbdhzepsbe .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#bbdhzepsbe .gt_font_normal {\n  font-weight: normal;\n}\n\n#bbdhzepsbe .gt_font_bold {\n  font-weight: bold;\n}\n\n#bbdhzepsbe .gt_font_italic {\n  font-style: italic;\n}\n\n#bbdhzepsbe .gt_super {\n  font-size: 65%;\n}\n\n#bbdhzepsbe .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#bbdhzepsbe .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#bbdhzepsbe .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#bbdhzepsbe .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#bbdhzepsbe .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#bbdhzepsbe .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#bbdhzepsbe .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#bbdhzepsbe .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#bbdhzepsbe div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"name\">Metric</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"value\">%</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"name\" class=\"gt_row gt_left\">Number of People</td>\n<td headers=\"value\" class=\"gt_row gt_right\">316.0</td></tr>\n    <tr><td headers=\"name\" class=\"gt_row gt_left\">Approval Rate</td>\n<td headers=\"value\" class=\"gt_row gt_right\">50.6</td></tr>\n    <tr><td headers=\"name\" class=\"gt_row gt_left\">Pct. Income Eligible</td>\n<td headers=\"value\" class=\"gt_row gt_right\">98.4</td></tr>\n    <tr><td headers=\"name\" class=\"gt_row gt_left\">Pct. Docs With App</td>\n<td headers=\"value\" class=\"gt_row gt_right\">46.5</td></tr>\n    <tr><td headers=\"name\" class=\"gt_row gt_left\">Pct. Docs Acfter App</td>\n<td headers=\"value\" class=\"gt_row gt_right\">24.4</td></tr>\n    <tr><td headers=\"name\" class=\"gt_row gt_left\">Pct. Completed Interview</td>\n<td headers=\"value\" class=\"gt_row gt_right\">31.3</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n<br>Observations:\n\n-   Nearly half of the gray zone applicants were approved\n-   99% appear income-eligible, but:\n    -   Only 38% submitted documents with their application\n    -   Only 22% completed the interview\n\nThis group represents a major opportunity: they’re likely eligible, but many didn’t complete the full process. Small nudges or reminders could meaningfully increase approvals.\n\n## Conclusion\n\nThis analysis examined patterns in CalFresh (SNAP) application outcomes among GetCalFresh.org users in San Diego County. Several process-related factors were strongly associated with whether an applicant was approved.\n\n::: callout-purple\n**Key Findings:**\n\n-   **Interview completion was the most predictive factor:** Applicants who reported completing the interview were nearly three times more likely to be approved. Their average predicted approval probability was 72%, compared to 50% for others.\n-   **Document uploads mattered:** Uploading verification documents — especially with the initial application — was associated with higher approval rates.\n-   **Higher income reduced the odds of approval:** Each additional $500 in income was associated with about a one-third decrease in approval odds — even among mostly income-eligible applicants.\n-   **Many income-eligible applicants were not approved:** Nearly half of income-eligible applicants were denied, suggesting process-related barriers (e.g., missing interviews or documents) play a major role.\n-   **ZIP code predicted approval differences:** Approval rates varied significantly by ZIP, pointing to geographic disparities in access or processing.\n-   **A large group fell into a “gray zone”:** Applicants with predicted approval probabilities between 40–59% were often income-eligible but missed key steps like interviews or document uploads. This group is a strong target for reminders or support.\n:::\n\n## Next Steps: Areas for Deeper Analysis\n\nThis section outlines follow-up analyses and design considerations to expand on the current findings and inform future improvements to the CalFresh application process.\n\n### Geographic and Neighborhood Variation\n\n-   Link ZIP codes to American Community Survey (ACS) indicators:\n    -   Poverty rate\n    -   Housing burden\n    -   Broadband access\n    -   Languages spoken at home\n-   Map approval rates by neighborhood to identify areas with potential access barriers\n-   Assess whether geographic disparities persist after controlling for applicant characteristics\n-   Immigration status is requested in the survey, which may influence both applicant behavior and caseworker decisions. Consider whether areas with larger immigrant populations experience different approval rates, potentially due to documentation fears, interview accessibility, or language support gaps.\n\n### Qualitative Research\n\n-   Interview applicants to:\n    -   Understand perceived barriers in the process\n    -   Identify confusing or unclear steps\n    -   Explore unmet needs for documentation or interview follow-up\n-   Review SMS or helpdesk interactions for common pain points\n\n### Timing and Process Flow\n\n-   Analyze time between:\n    -   Application start and finish\n    -   Application and document upload\n    -   Application and interview completion\n-   Identify drop-off points or common delays in the flow\n-   Explore whether earlier intervention (e.g., reminders) affects outcomes\n\n### System and Policy Implications\n\n-   Share ZIP-level insights with county caseworkers and program administrators\n-   Evaluate platform changes (e.g., nudges, scheduling tools, help prompts) for impact on completion and approval\n-   Explore partnerships for assisted application support in low-approval ZIPs\n\n\n\n\n",
    "supporting": [
      "analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/core-js-2.5.3/shim.min.js\"></script>\n<script src=\"site_libs/react-18.2.0/react.min.js\"></script>\n<script src=\"site_libs/react-18.2.0/react-dom.min.js\"></script>\n<script src=\"site_libs/reactwidget-2.0.0/react-tools.js\"></script>\n<link href=\"site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"site_libs/reactable-0.4.4/reactable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/reactable-binding-0.4.4/reactable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}